PREFIX ?= /usr/local
BINARY_NAME = apfel-gui
VERSION_FILE = .version

.PHONY: build install uninstall clean bump-patch bump-minor bump-major generate-build-info release-patch release-minor release-major version

# --- Build ---

build: generate-build-info
	swift build -c release

install: build
	@# If Homebrew apfel-gui is linked and would shadow our install, unlink it.
	@# This only removes the symlink - the Homebrew package stays installed.
	@# `brew upgrade apfel-gui` or `brew link apfel-gui` restores it.
	@if command -v brew >/dev/null 2>&1 && brew list apfel-gui >/dev/null 2>&1; then \
		brew_path=$$(brew --prefix)/bin/$(BINARY_NAME); \
		if [ -L "$$brew_path" ]; then \
			echo "unlinking Homebrew apfel-gui (dev build takes priority)..."; \
			brew unlink apfel-gui 2>/dev/null || true; \
		fi; \
	fi
	@if [ -w "$(PREFIX)/bin" ]; then \
		mkdir -p $(PREFIX)/bin; \
		install .build/release/$(BINARY_NAME) $(PREFIX)/bin/$(BINARY_NAME); \
		mkdir -p $(PREFIX)/share/apfel-gui/mcp/debug-tools; \
		cp mcp/debug-tools/server.py $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py; \
		chmod +x $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py; \
	else \
		sudo mkdir -p $(PREFIX)/bin; \
		sudo install .build/release/$(BINARY_NAME) $(PREFIX)/bin/$(BINARY_NAME); \
		sudo mkdir -p $(PREFIX)/share/apfel-gui/mcp/debug-tools; \
		sudo cp mcp/debug-tools/server.py $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py; \
		sudo chmod +x $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py; \
	fi
	@echo "Installed $(BINARY_NAME) to $(PREFIX)/bin/$(BINARY_NAME)"
	@echo "Installed MCP debug-tools to $(PREFIX)/share/apfel-gui/mcp/debug-tools/"
	@resolved=$$(which $(BINARY_NAME) 2>/dev/null || echo "not in PATH"); \
	if [ "$$resolved" != "$(PREFIX)/bin/$(BINARY_NAME)" ]; then \
		echo "warning: 'which $(BINARY_NAME)' resolves to $$resolved, not $(PREFIX)/bin/$(BINARY_NAME)"; \
		echo "  Run: brew unlink apfel-gui   (then make install again)"; \
	fi

# --- Version bumps (used by release targets only) ---

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

# --- Release targets (version bump + build, used by release workflow only) ---

release-patch: bump-patch generate-build-info
	swift build -c release

release-minor: bump-minor generate-build-info
	swift build -c release

release-major: bump-major generate-build-info
	swift build -c release

# --- Generated files ---

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	branch=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"); \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make - do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

# --- Utilities ---

version:
	@cat $(VERSION_FILE)

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		rm -f $(PREFIX)/bin/$(BINARY_NAME); \
		rm -rf $(PREFIX)/share/apfel-gui; \
	else \
		sudo rm -f $(PREFIX)/bin/$(BINARY_NAME); \
		sudo rm -rf $(PREFIX)/share/apfel-gui; \
	fi
	@# Restore Homebrew apfel-gui if it was unlinked by make install.
	@if command -v brew >/dev/null 2>&1 && brew list apfel-gui >/dev/null 2>&1; then \
		if ! [ -L "$$(brew --prefix)/bin/$(BINARY_NAME)" ]; then \
			echo "restoring Homebrew apfel-gui link..."; \
			brew link apfel-gui 2>/dev/null || true; \
		fi; \
	fi

clean:
	swift package clean
	rm -rf .build
	rm -f Sources/BuildInfo.swift
