PREFIX ?= /usr/local
BINARY_NAME = apfel-gui
VERSION_FILE = .version

.PHONY: build install clean bump-patch generate-build-info release-minor release-major

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

release-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

release-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	branch=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"); \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make — do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

build: bump-patch generate-build-info
	swift build -c release

install: build
	@mkdir -p $(PREFIX)/bin
	@cp .build/release/$(BINARY_NAME) $(PREFIX)/bin/$(BINARY_NAME)
	@mkdir -p $(PREFIX)/share/apfel-gui/mcp/debug-tools
	@cp mcp/debug-tools/server.py $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py
	@chmod +x $(PREFIX)/share/apfel-gui/mcp/debug-tools/server.py
	@echo "Installed $(BINARY_NAME) to $(PREFIX)/bin/$(BINARY_NAME)"
	@echo "Installed MCP debug-tools to $(PREFIX)/share/apfel-gui/mcp/debug-tools/"

clean:
	swift package clean
	rm -rf .build
	rm -f Sources/BuildInfo.swift
